### ISSUE TITLE
Save as PNG

### ISSUE THREAD

**Issue by lucijanblagonic** [lucijanblagonic/wceu-logo-generator#6]
We got comments that saving it as PNG would be helpful as well! @tekindermisel do you have any idea how we could add this?

**Comment by tekindermisel** [comment]
Let me do a short research on this one. :)

**Comment by lucijanblagonic** [comment]
Not sure if Canvas is a way to go here, but check it out http://html2canvas.hertzen.com/examples.html

**Comment by tekindermisel** [comment]
No, there is no need to involve canvas. There is js library for this stuff.

**Comment by tekindermisel** [comment]
Done
