### ISSUE TITLE
Share your customized logo as a link

### ISSUE THREAD

**Issue by lucijanblagonic** [lucijanblagonic/wceu-logo-generator#8]
One of the features we are missing is being able to share the customized logo as a link. This could probably be done through the URL directly, like color scheme generators [often do](https://coolors.co/d7dedc-cfcfcd-9a879d-7a3b69-563440) — any chance we could add this functionality to our app?

We could then create a collection of interesting logo ideas for future events and past events, or simply to explore ideas.

**Comment by tekindermisel** [comment]
Adding this is a little longer work since we need to create a data flow from few directions: URL and input fields.

**Comment by tekindermisel** [comment]
By default, we can insert any kind of params to URL simply by doing this: www.google.com?paramOne=paramOneValue&paramTwo=paramTwoValue, and this comes by default. I'm not sure how to do a customized params like this: www.google.com/#f2f2f2-#f2f2f2-#f2f2f2-#f2f2f2

**Comment by lucijanblagonic** [comment]
The one you suggested is good enough. I've just sent that one as an example.

In that case it's important that as soon as someone changes the color, the link is updated. That should work for the focus as well — when a specific dot is clicked, it should be remembered in the address bar.

Makes sense?

**Comment by tekindermisel** [comment]
@lucijanblagonic can you test this and make sure it works! :)
